# Generated by Django 5.2.4 on 2026-01-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('attack_power', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('potion', 'Potion'), ('weapon', 'Weapon'), ('shield', 'Shield'), ('treasure', 'Treasure')], max_length=20)),
                ('effect_value', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
