# Generated by Django 5.2.4 on 2026-01-10 10:21

from django.db import migrations


def create_sample_data(apps, schema_editor):
    Enemy = apps.get_model('game', 'Enemy')
    Item = apps.get_model('game', 'Item')
    
    # Create enemies
    enemies = [
        Enemy(name='Goblin', health=30, attack_power=8, description='A small but fierce creature with sharp claws.'),
        Enemy(name='Orc', health=50, attack_power=12, description='A large, brutish warrior with heavy armor.'),
        Enemy(name='Skeleton', health=25, attack_power=10, description='An undead warrior wielding a rusty sword.'),
        Enemy(name='Troll', health=80, attack_power=15, description='A massive, regenerating creature with incredible strength.'),
        Enemy(name='Dark Wizard', health=40, attack_power=18, description='A powerful spellcaster wielding dark magic.'),
        Enemy(name='Wolf', health=35, attack_power=11, description='A ferocious predator with sharp teeth.'),
        Enemy(name='Dragon', health=100, attack_power=20, description='A legendary beast with fiery breath.'),
        Enemy(name='Assassin', health=45, attack_power=16, description='A stealthy killer with deadly blades.'),
    ]
    
    for enemy in enemies:
        enemy.save()
    
    # Create items
    items = [
        Item(name='Health Potion', item_type='potion', effect_value=25, description='A red liquid that restores health.'),
        Item(name='Strong Health Potion', item_type='potion', effect_value=50, description='A powerful elixir that restores significant health.'),
        Item(name='Iron Sword', item_type='weapon', effect_value=5, description='A sturdy sword that increases attack power.'),
        Item(name='Magic Staff', item_type='weapon', effect_value=8, description='A mystical staff that channels magical energy.'),
        Item(name='Wooden Shield', item_type='shield', effect_value=3, description='A basic shield that provides protection.'),
        Item(name='Gold Coin', item_type='treasure', effect_value=10, description='A shiny gold coin.'),
        Item(name='Ruby Gem', item_type='treasure', effect_value=25, description='A precious red gemstone.'),
        Item(name='Ancient Artifact', item_type='treasure', effect_value=50, description='A mysterious artifact of great value.'),
    ]
    
    for item in items:
        item.save()


def remove_sample_data(apps, schema_editor):
    Enemy = apps.get_model('game', 'Enemy')
    Item = apps.get_model('game', 'Item')
    
    Enemy.objects.all().delete()
    Item.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, remove_sample_data),
    ]
